name: Continuous Deployment

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  deployment:
    runs-on: ubuntu-latest
    name: CD
    steps:
      - name: Publishing
        run: echo "deployment success"
